window.BTOS_ARTISTS = [
  {
    "id": "grooverider",
    "name": "Grooverider",
    "role": "DJ",
    "public": true,
    "activeFrom": 1985,
    "archiveTo": 2005,
    "origin": "South London, England",
    "styles": [
      "House",
      "Breakbeat Hardcore",
      "Jungle",
      "Drum & Bass"
    ],
    "image": "grooverider.jpg",
    "photoCredit": "Alkivar, 2004 · CC BY-SA 2.5",
    "summary": "Jungle pioneer, broadcaster, producer and founder of Prototype Recordings.",
    "biography": [
      "Grooverider emerged from London’s mid-1980s pirate-radio and club network before becoming central to the evolution from house and breakbeat hardcore into jungle and drum & bass.",
      "His partnership with Fabio and their Rage residency at Heaven helped establish a space where new breakbeat and bass-driven music could develop.",
      "Through Prototype Recordings, production work, radio and international touring, he remained a major figure through the archive period ending in 2005."
    ],
    "timeline": [
      {
        "year": "Mid-1980s",
        "title": "Pirate radio and early DJ work",
        "text": "Early London broadcasts and club sets."
      },
      {
        "year": "1988–1991",
        "title": "House, hardcore and Rage",
        "text": "The Fabio and Grooverider partnership became central to London’s changing rave sound."
      },
      {
        "year": "1991",
        "title": "Helter Skelter recording",
        "text": "A confirmed Grooverider recording survives from Milwaukees."
      },
      {
        "year": "1993–1998",
        "title": "Jungle, Prototype and album work",
        "text": "Production aliases, Prototype Recordings and major releases expanded his influence."
      },
      {
        "year": "1999–2005",
        "title": "Radio and international activity",
        "text": "Continued broadcasting, touring and label activity."
      }
    ],
    "tapes": [
      {
        "title": "Helter Skelter — Milwaukees, 1991",
        "href": "packs.html?artist=grooverider"
      }
    ],
    "flyers": [
      {
        "title": "Grooverider flyer appearances",
        "href": "flyers.html?artist=grooverider"
      }
    ],
    "events": [
      {
        "title": "Grooverider event appearances",
        "href": "events.html?artist=grooverider"
      }
    ],
    "sources": [
      {
        "title": "Metalheadz artist biography",
        "href": "https://www.metalheadz.co.uk/artist/grooverider"
      },
      {
        "title": "Wikimedia Commons photograph",
        "href": "https://commons.wikimedia.org/wiki/File:Grooverider.JPG"
      }
    ]
  },
  {
    "id": "mc-det",
    "name": "MC Det",
    "role": "MC",
    "public": true,
    "activeFrom": 1988,
    "archiveTo": 2005,
    "origin": "United Kingdom",
    "styles": [
      "Jungle",
      "Drum & Bass",
      "Rap"
    ],
    "image": "mcdet.webp",
    "photoCredit": "Rinse FM",
    "summary": "Veteran jungle and drum & bass MC linked to pirate radio, rave stages and recorded projects.",
    "biography": [
      "MC Det is associated with the development of UK jungle and drum & bass MC culture, pirate radio and major live events.",
      "His work also crossed into recorded releases and collaborations outside the traditional rave-MC format."
    ],
    "timeline": [
      {
        "year": "Late 1980s–early 1990s",
        "title": "Underground scene",
        "text": "Early activity in London’s developing rave and radio networks."
      },
      {
        "year": "1995",
        "title": "Out of Det",
        "text": "Recorded-project milestone during the jungle era."
      },
      {
        "year": "1996–2005",
        "title": "Radio, events and collaborations",
        "text": "Continued MC and collaborative activity through the archive period."
      }
    ],
    "tapes": [
      {
        "title": "MC Det tape and radio recordings",
        "href": "packs.html?artist=mc-det"
      }
    ],
    "flyers": [
      {
        "title": "MC Det flyer appearances",
        "href": "flyers.html?artist=mc-det"
      }
    ],
    "events": [
      {
        "title": "MC Det event appearances",
        "href": "events.html?artist=mc-det"
      }
    ],
    "sources": [
      {
        "title": "Rinse FM profile",
        "href": "https://www.rinse.fm/shows/mc-det"
      }
    ]
  },
  {
    "id": "ltj-bukem",
    "name": "LTJ Bukem",
    "role": "DJ",
    "public": true,
    "activeFrom": 1988,
    "archiveTo": 2005,
    "origin": "London, England",
    "styles": [
      "Jungle",
      "Drum & Bass"
    ],
    "image": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Ltjbukem1.jpg",
    "photoCredit": "Wikimedia Commons source",
    "summary": "DJ, producer and Good Looking Records founder associated with atmospheric drum & bass.",
    "biography": [
      "Starter profile active for system testing. Full sourced history and dated photographic timeline are scheduled for research."
    ],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": []
  },
  {
    "id": "dj-hype",
    "name": "DJ Hype",
    "role": "DJ",
    "public": true,
    "activeFrom": 1988,
    "archiveTo": 2005,
    "origin": "London, England",
    "styles": [
      "Hardcore",
      "Jungle",
      "Drum & Bass"
    ],
    "image": "https://commons.wikimedia.org/wiki/Special:Redirect/file/DJ_Hype_at_Egg_(2018).jpg",
    "photoCredit": "Wikimedia Commons source",
    "summary": "DJ and producer associated with breakbeat hardcore, jungle, drum & bass and Ganja Records.",
    "biography": [
      "Starter profile active for system testing. Full sourced history and dated photographic timeline are scheduled for research."
    ],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": []
  },
  {
    "id": "shy-fx",
    "name": "Shy FX",
    "role": "DJ",
    "public": true,
    "activeFrom": 1992,
    "archiveTo": 2005,
    "origin": "London, England",
    "styles": [
      "Jungle",
      "Drum & Bass"
    ],
    "image": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Shy_FX.jpg",
    "photoCredit": "Wikimedia Commons source",
    "summary": "Jungle and drum & bass DJ and producer.",
    "biography": [
      "Starter profile active for system testing. Full sourced history and dated photographic timeline are scheduled for research."
    ],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": []
  },
  {
    "id": "roni-size",
    "name": "Roni Size",
    "role": "DJ",
    "public": true,
    "activeFrom": 1988,
    "archiveTo": 2005,
    "origin": "Bristol, England",
    "styles": [
      "Jungle",
      "Drum & Bass"
    ],
    "image": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Roni_Size_09.jpg",
    "photoCredit": "Wikimedia Commons source",
    "summary": "Bristol DJ, producer and member of Reprazent.",
    "biography": [
      "Starter profile active for system testing. Full sourced history and dated photographic timeline are scheduled for research."
    ],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": []
  },
  {
    "id": "fabio",
    "name": "Fabio",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": []
  },
  {
    "id": "carl-cox",
    "name": "Carl Cox",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": []
  },
  {
    "id": "jumping-jack-frost",
    "name": "Jumping Jack Frost",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": []
  },
  {
    "id": "mickey-finn",
    "name": "Mickey Finn",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": []
  },
  {
    "id": "randall",
    "name": "Randall",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": []
  },
  {
    "id": "slipmatt",
    "name": "Slipmatt",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": []
  },
  {
    "id": "ellis-dee",
    "name": "Ellis Dee",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": []
  },
  {
    "id": "easygroove",
    "name": "Easygroove",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": []
  },
  {
    "id": "kenny-ken",
    "name": "Kenny Ken",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": []
  },
  {
    "id": "dj-ss",
    "name": "DJ SS",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": []
  },
  {
    "id": "ratty",
    "name": "Ratty",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": []
  },
  {
    "id": "mc-gq",
    "name": "MC GQ",
    "role": "MC",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": []
  },
  {
    "id": "mc-fearless",
    "name": "MC Fearless",
    "role": "MC",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": []
  },
  {
    "id": "mc-sharkey",
    "name": "MC Sharkey",
    "role": "MC",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": []
  },
  {
    "id": "adamski",
    "name": "Adamski",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "altern-8",
    "name": "Altern 8",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "andy-c",
    "name": "Andy C",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "andy-farley",
    "name": "Andy Farley",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "andy-weatherall",
    "name": "Andrew Weatherall",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "bad-company-uk",
    "name": "Bad Company UK",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "billy-daniel-bunter",
    "name": "Billy Daniel Bunter",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "brisk",
    "name": "Brisk",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "brockie",
    "name": "Brockie",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "clarkee",
    "name": "Clarkee",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "colin-dale",
    "name": "Colin Dale",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "colin-faver",
    "name": "Colin Faver",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "darren-jay",
    "name": "Darren Jay",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "dj-dazee",
    "name": "DJ Dazee",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "dj-dexxtrous",
    "name": "DJ Dextrous",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "dj-dna",
    "name": "DJ DNA",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "dj-dougal",
    "name": "DJ Dougal",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "dj-fierce",
    "name": "DJ Fierce",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "dj-gammon",
    "name": "DJ Gammon",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "dj-kane",
    "name": "DJ Kane",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "dj-lime",
    "name": "DJ Lime",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "dj-rap",
    "name": "DJ Rap",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "dj-seduction",
    "name": "DJ Seduction",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "dj-swan-e",
    "name": "DJ Swan-E",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "dj-vibes",
    "name": "DJ Vibes",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "doc-scott",
    "name": "Doc Scott",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "dr-s-gachet",
    "name": "Dr S Gachet",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "eddie-richards",
    "name": "Eddie Richards",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "easy-d",
    "name": "Easy D",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "force-and-styles",
    "name": "Force & Styles",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "frankie-bones",
    "name": "Frankie Bones",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "frankie-valentine",
    "name": "Frankie Valentine",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "goldie",
    "name": "Goldie",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "greg-packer",
    "name": "Greg Packer",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "john-digweed",
    "name": "John Digweed",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "jon-pleased-wimmin",
    "name": "Jon Pleased Wimmin",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "keoki",
    "name": "Keoki",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "krome-and-time",
    "name": "Krome & Time",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "lenny-dee",
    "name": "Lenny Dee",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "marcus-intalex",
    "name": "Marcus Intalex",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "mark-eg",
    "name": "Mark EG",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "mike-dred",
    "name": "Mike Dred",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "nicky-blackmarket",
    "name": "Nicky Blackmarket",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "paul-oakenfold",
    "name": "Paul Oakenfold",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "paul-trouble-anderson",
    "name": "Paul Trouble Anderson",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "pilgrim",
    "name": "Pilgrim",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "ray-keith",
    "name": "Ray Keith",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "rhythm-doctor",
    "name": "Rhythm Doctor",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "richie-fingers",
    "name": "Richie Fingers",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "rob-playford",
    "name": "Rob Playford",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "sasha",
    "name": "Sasha",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "simon-bassline-smith",
    "name": "Simon Bassline Smith",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "stu-allan",
    "name": "Stu Allan",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "stuart-banks",
    "name": "Stuart Banks",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "sven-vath",
    "name": "Sven Väth",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "sy",
    "name": "Sy",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "tango",
    "name": "Tango",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "top-buzz",
    "name": "Top Buzz",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "trevor-rockliffe",
    "name": "Trevor Rockliffe",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "vinylgroover",
    "name": "Vinylgroover",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "warlock",
    "name": "Warlock",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "zinc",
    "name": "DJ Zinc",
    "role": "DJ",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "mc-conrad",
    "name": "MC Conrad",
    "role": "MC",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "mc-fats",
    "name": "MC Fats",
    "role": "MC",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "mc-hyper-d",
    "name": "MC Hyper D",
    "role": "MC",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "mc-ribbz",
    "name": "MC Ribbz",
    "role": "MC",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "mc-ruff",
    "name": "MC Ruff",
    "role": "MC",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "mc-storm",
    "name": "MC Storm",
    "role": "MC",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "mc-whizzkid",
    "name": "MC Whizzkid",
    "role": "MC",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "mc-trigger",
    "name": "MC Trigger",
    "role": "MC",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "mc-moose",
    "name": "MC Moose",
    "role": "MC",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "mc-mad-p",
    "name": "MC Mad P",
    "role": "MC",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "mc-charlie-b",
    "name": "MC Charlie B",
    "role": "MC",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "mc-motormouth",
    "name": "MC Motormouth",
    "role": "MC",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "mc-odyssey",
    "name": "MC Odyssey",
    "role": "MC",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "mc-raw",
    "name": "MC Raw",
    "role": "MC",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "mc-rebel",
    "name": "MC Rebel",
    "role": "MC",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "mc-rage",
    "name": "MC Rage",
    "role": "MC",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "mc-livelee",
    "name": "MC Livelee",
    "role": "MC",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  },
  {
    "id": "mc-junior-red",
    "name": "MC Junior Red",
    "role": "MC",
    "public": false,
    "activeFrom": null,
    "archiveTo": 2005,
    "origin": "",
    "styles": [],
    "image": "",
    "photoCredit": "",
    "summary": "",
    "biography": [],
    "timeline": [],
    "tapes": [],
    "flyers": [],
    "events": [],
    "sources": [],
    "researchStatus": "queued"
  }
];
